### ISSUE TITLE
Why do you use "\" instead of "/"?

### ISSUE THREAD

**Issue by pedrorriva** [gilbertocortez/facebook_conversions#1]
I had to change all of the relative paths for the code to work for me, such as "include 'inc/objects/curl.class.php';", After doing so, I was able to use the code, which works perfectly btw.

**Comment by gilbertocortez** [comment]
Hi! Glad the code was able to be of help to you. I was unable to find the area you mentioned with a "\" could you please provide further clarification.

**Comment by pedrorriva** [comment]
You probably developed this on a Windows machine, that's why you use \ instead of / in URLs (both of them are accepted by windows). My server runs on UNIX, which uses only / for URLs - it does not accept \ in a path. My recommendation is that, when including the curl.class.php file, you should use / in your URLs instead of \  so that it would work out of the box for Linux/Unix servers too, not only windows (windows accepts both \ and / in URLs)

**Comment by nititoken** [comment]
> You probably developed this on a Windows machine, that's why you use \ instead of / in URLs (both of them are accepted by windows). My server runs on UNIX, which uses only / for URLs - it does not accept \ in a path. My recommendation is that, when including the curl.class.php file, you should use / in your URLs instead of \ so that it would work out of the box for Linux/Unix servers too, not only windows (windows accepts both \ and / in URLs)

There's no use of \ anywhere in the code.

**Comment by gilbertocortez** [comment]
Unable to find use of \ in code. If found on your local copy, please make sure to change it to the correct patch. Closing Case.
